---
title: "Machine Learning Models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Machine Learning Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette show the basic functionality related to building and using machine learning models in `XIFF` package.

```{r setup}
library(XIFF)

# Model training

data("data_createMachineLearningModel", package = "XIFF")
trainingSet <- data_createMachineLearningModel$trainingSet
geneSet     <- data_createMachineLearningModel$geneSet
geneAnno    <- data_createMachineLearningModel$geneAnno

test_time <- function(expr) {
  cr <- match.call()
  time <- system.time(res <- eval(expr))
  message("Running ", cr, " took ", round(time[[3]], 2), "seconds")
  res
}

fitNN <- test_time(createMachineLearningModel(trainingSet, geneSet, geneAnno, method = "neuralnetwork"))
fitRf <- test_time(createMachineLearningModel(trainingSet, geneSet, geneAnno))

# Use different feature selection algorithm
fitRfColTest <- test_time(createMachineLearningModel(trainingSet, geneSet, geneAnno, selectBestFeaturesFnc = selectBestFeaturesTTest, threshold = 0.05))
```
Saving and loading the model

```{r}
# Save machine learning model
mlResNN <- machineLearningResult(fitNN, fitNN$model$classLabel)
mlResRf   <- machineLearningResult(fitRf, fitRf$model$classLabel)

fileNN <- tempfile(fileext = ".rds")
fileRf <- tempfile(fileext = ".rds")
saveRDS(mlResNN, fileNN)
saveRDS(mlResRf, fileRf)

loadedFileNN <- loadMachineLearningModel(fileNN)
loadedFileRf <- loadMachineLearningModel(fileRf)

data <- loadedFileNN$model$data

predictFromModel(loadedFileNN, data)
predictFromModel(loadedFileRf, data)

XIFF::getVarImp(fitNN$model$model)
XIFF::getVarImp(fitRf$model$model)
```
